services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    volumes:
      - postgres_chat_data:/var/lib/postgresql/data
    networks:
      - chat_network
      
  api:
    image: chat_manager_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Database=chat;Username=postgres;Password=postgres
    depends_on:
      - db
    networks:
      - chat_network

  api_development:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: chat_manager_dev
    volumes:
      - .:/workspace
    networks:
      - chat_network
    depends_on:
      - db
    command: sleep infinity

volumes:
  postgres_chat_data:

networks:
  chat_network:
    name: chat_server_network
    driver: bridge